name: Synchronize LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: lduran2/my-leetcode-sync@v1.3
      with:
        github-token: ${{ github.token }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
